apiVersion: v1
kind: Service
metadata:
  name: post-like-cluster-ip
spec:
  selector:
    service: post-like
  ports:
    - name: post-like-cluster-ip
      protocol: TCP
      port: 3000
      targetPort: 3000
