apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: marius24/authentication-service
      context: authentication-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src"
            dest: .
    - image: marius24/email-service
      context: email-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src"
            dest: .
    - image: marius24/post-service
      context: post-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src"
            dest: .
    - image: marius24/comment-service
      context: comment-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src"
            dest: .
