apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: post
  template:
    metadata:
      labels:
        service: post
    spec:
      containers:
        - name: post
          image: marius24/post-service
          env:
            - name: NODE_ENV
              value: "development"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-cluster-ip:4222"
            - name: NATS_CLUSTER_ID
              value: connectix
