apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: comment
  template:
    metadata:
      labels:
        service: comment
    spec:
      containers:
        - name: comment
          image: marius24/comment-service
          env:
            - name: NODE_ENV
              value: "development"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-cluster-ip:4222"
            - name: NATS_CLUSTER_ID
              value: connectix
