apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip
spec:
  selector:
    service: client
  ports:
    - name: client-cluster-ip
      protocol: TCP
      port: 3000
      targetPort: 3000
