apiVersion: v1
kind: Service
metadata:
  name: authentication-cluster-ip
spec:
  selector:
    service: authentication
  ports:
    - name: authentication-cluster-ip
      protocol: TCP
      port: 3000
      targetPort: 3000
