apiVersion: v1
kind: Service
metadata:
  name: comment-cluster-ip
spec:
  selector:
    service: comment
  ports:
    - name: comment-cluster-ip
      protocol: TCP
      port: 3000
      targetPort: 3000
