apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: client
  template:
    metadata:
      labels:
        service: client
    spec:
      containers:
        - name: client
          image: marius24/client-service
          env:
            - name: NODE_ENV
              value: "development"
