apiVersion: v1
kind: Service
metadata:
  name: following-cluster-ip
spec:
  selector:
    service: following
  ports:
    - name: following-cluster-ip
      protocol: TCP
      port: 3000
      targetPort: 3000
